---

spring:
  sql:
    init:
      mode: always
  application:
    name: EmployeeApp
  main:
    allow-bean-definition-overriding: true
  datasource:
    embedded-database-connection: h2
    url: jdbc:h2:mem:employee-db

server:
  port: 4567

jwt:
  key: ${JWT_KEY:someDefaultSuperLongSecretString}
  token-expiration: 120000
  refresh-token-expiration: 480000

security:
  permitted-endpoints:
    - /api/auth
    - /api/auth/refresh
    - /error
  admin-endpoints:
    - /api/employees**
